name: my first workflow
on: [push , fork]
jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: welcome message
              run: echo "my first github action flow"
            - name : list files
              run: ls
            - name: read file
              run: cat READMD.md
            
